name: 'Fuck Deploy'
description: 'Using Github Actions deploy it to server with password or private_key'
author: 'jamesyang <i@xhlr.top>'
branding:
  icon: 'upload-cloud'
  color: 'green'
inputs:
  type:
    description: ''
    required: true
  username:
    description: 'Server username'
    required: true
  host:
    description: 'IP'
    required: true
  port:
    description: ''
    default: 22
  password:
    description: 'password'
  private_key:
    description: 'Private Key'
  remote_path:
    description: ''
    required: true
  local_path:
    description: ''
    default: './'
  include:
    description: ''
    #required: true
  exclude:
    description: ''
    #default: '.env'
  args:
    description: 'rsync args'
runs:
  using: 'docker'
  image: 'Dockerfile'
