name: 'Fuck Deploy'
description: 'Use rsync with SSH and SSHPASS to deploy project in server'
author: 'jamesyang <i@xhlr.top>'
branding:
  icon: 'upload-cloud'
  color: 'green'
inputs:
  type:
    description: ''
    required: true
  username:
    description: 'Server username'
    required: true
  password:
    description: 'password'
  key:
    description: 'Private Key'
  host:
    description: 'IP'
    required: true
  port:
    description: ''
    default: 22
  remote_path:
    description: ''
    required: true
  local_path:
    description: ''
    default: './*'
  include:
    description: ''
  exclude:
    description: ''
  args:
    description: 'rsync args'
    default: '-ratlz'
  ssh_args:
    description: 'ssh args'
    default: '-o ConnectTimeout=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
  scripts:
    description: 'deployment scripts'
runs:
  using: 'docker'
  image: 'Dockerfile'
