# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Fuck Deploy'
description: 'Use rsync with SSH and SSHPASS to deploy project in server'
author: 'jamesyang <i@xhlr.top>'
branding:
  icon: 'upload-cloud'
  color: 'green'
inputs:
  type:
    description: 'Authentication Method'
    required: true
  username:
    description: 'Remote Server Username'
    required: true
  password:
    description: 'Remote Server Password'
  key:
    description: 'Private Key'
  host:
    description: 'Remote Server IP or Domain Name'
    required: true
  port:
    description: 'Remote Server Port'
    default: 22
  remote_path:
    description: 'Remote Server Path'
    required: true
  local_path:
    description: 'Github Runner Local Path'
    default: './*'
  include:
    description: 'Include Files or Directory'
  exclude:
    description: 'Exclude Files or Directory'
  args:
    description: 'Rsync Arguments'
    default: '-ratlz'
  ssh_args:
    description: 'SSH Arguments'
    default: '-o ConnectTimeout=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
  script:
    description: 'deployment script'
runs:
  using: 'docker'
  image: 'Dockerfile'
