on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: llxlr/fuck-deploy@master
      with:
        type: 'password'
        username: 'root'
        password: '123456'
        host: '127.0.0.1'
        port: 22
        remote_path: '/www/wwwroot/default/'
        local_path: './'
        include:
          - 'a.txt'
        exclude:
          - '.env'
        args: '-o FakeOption'
        scripts:
          path: 'deploy.sh'
          args: 'prod'
  job2:
    runs-on: ubuntu-latest
    steps:
    - uses: llxlr/fuck-deploy@master
      with:
        type: 'key'
        username: 'root'
        key: '${{ secrets.KEY }}'
        host: '127.0.0.1'
        port: 22
        remote_path: '/www/wwwroot/default/'
        local_path: './'
        include:
          - 'a.txt'
        exclude:
          - '.env'
        args: '-o FakeOption'
        scripts:
          path: 'deploy.sh'
          args: 'dev'
