name: Test

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: llxlr/fuck-deploy@master
      with:
        type: 'password'
        username: 'root'
        password: '123456'
        host: '127.0.0.1'
        port: 22
        remote_path: '/www/wwwroot/default/'
        local_path: './'
        include: |
          'a.txt'
          'b.txt'
        exclude: |
          '.env'
          '.env.prod'
        args: '-o FakeOption'
        script: 'deploy.sh'
      env:
        Environment: 'prod'

  job2:
    runs-on: ubuntu-latest
    steps:
    - uses: llxlr/fuck-deploy@master
      with:
        type: 'key'
        username: 'root'
        key: '${{ secrets.KEY }}'
        host: '127.0.0.1'
        port: 22
        remote_path: '/www/wwwroot/default/'
        local_path: './'
        include: |
          'a.txt'
          'b.txt'
        exclude: |
          '.env'
          '.env.prod'
        args: '-o FakeOption'
        script: 'deploy.sh'
      env:
        Environment: 'dev'
