on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
    - name: Deployment
      uses: llxlr/fuck-deploy@master
      with:
        type: 'password'
        username: 'root'
        host: '127.0.0.1'
        port: 22
        password: '123456'
        #private_key: 
        remote_path: '/www/wwwroot/default/'
        local_path: './'
        include: 'a.txt'
        exclude: '.env'
        args: '-o FakeOption'
